export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const DISPLAY_FAILURE_MESSAGE = 'DISPLAY_FAILURE_MESSAGE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SEARCH_FAILURE_MESSAGE = 'SEARCH_FAILURE_MESSAGE';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
